import { NextResponse } from 'next/server';

// Mock audio URLs - in a real application, these would be generated by a text-to-speech service
// like ElevenLabs, Amazon Polly, or Google Text-to-Speech API
const mockAudioUrls = [
  'https://audio-samples.github.io/samples/mp3/blizzard_biased/sample-1.mp3',
  'https://audio-samples.github.io/samples/mp3/blizzard_biased/sample-2.mp3',
  'https://audio-samples.github.io/samples/mp3/blizzard_biased/sample-3.mp3',
  'https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-1.mp3',
  'https://audio-samples.github.io/samples/mp3/blizzard_unconditional/sample-2.mp3'
];

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { text } = body;
    
    if (!text) {
      return NextResponse.json(
        { error: 'Text is required' },
        { status: 400 }
      );
    }
    
    // Simulate processing time for text-to-speech generation
    await new Promise(resolve => setTimeout(resolve, 800));
    
    // Select a random mock audio URL
    const randomIndex = Math.floor(Math.random() * mockAudioUrls.length);
    const audioUrl = mockAudioUrls[randomIndex];
    
    return NextResponse.json({
      audioUrl,
      text,
      success: true
    });
  } catch (error) {
    console.error('Error generating voice audio:', error);
    return NextResponse.json(
      { error: 'Failed to generate voice audio' },
      { status: 500 }
    );
  }
} 